### ISSUE TITLE
Do you need face?

### ISSUE THREAD

**Issue by curehabit** [waahah/async-spider#1]
How can a person be so shameless?
一个人怎么能这么不要脸呢？
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/21287610/206351345-af375a10-d8e7-40dc-8ca6-b84b0e962418.png">
<img width="1746" alt="image" src="https://user-images.githubusercontent.com/21287610/206351384-a888aad5-b8d2-4367-b1ae-0b23748c2c0d.png">
<img width="1742" alt="image" src="https://user-images.githubusercontent.com/21287610/206351436-8cf91f07-b968-4252-bf67-d6c05c63abf8.png">
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/21287610/206351811-d91a7bd4-fb9c-49b0-ab48-39f321f45c1f.png">
https://www.52pojie.cn/thread-1718850-1-1.html

**Comment by curehabit** [comment]
<img width="899" alt="image" src="https://user-images.githubusercontent.com/21287610/206352019-b1f59bb1-13d6-45fe-89f7-6286abda4440.png">

**Comment by waahah** [comment]
感谢光临😄😄😄，嘻嘻

**Comment by Zptpierce** [comment]
竟然还开源了，Lmao

**Comment by waahah** [comment]
> 竟然还开源了，Lmao

Isn't it normal to put the code in github? What's strange
